### ISSUE TITLE
Is it possible to change the characters in the built-in interface?

### ISSUE THREAD

**Issue by taka0913** [Shanyaliux/SerialPortSample#1]
The built-in interface displayed by openDiscoveryActivity () is Chinese.
I want to change each character on the screen of that built-in interface.
Is there any way?
Or could you support it with an update?

**Comment by Shanyaliux** [comment]
It is expected that all built-in characters will support English and Chinese in the next version. This version will be released soon.
If you need it urgently or have other modifications, you can fork the source code and modify it yourself. Of course, you can always contact me if you have any questions.

**Comment by Shanyaliux** [comment]
New version 4.1.8 to support English. You can update using.
### Uasge
```
repositories {
  google()
  mavenCentral()
}

dependencies {
    implementation 'cn.shanyaliux.serialport:serialport:4.1.8'
}
```
